name: 'Build Quasar Android'
description: Action to build 
inputs:
  search-values: 
    description: Search values to find and replace with replace-values (~ is the delimiter)
    required: false
  replace-values: 
    description: Replace values to replace the search-values with (~ is the delimiter)
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Replacements
      run: |
        IFS='~' read -ra SEARCH <<< "${{ inputs.search-values }}"
        IFS='~' read -ra REPLACE <<< "${{ inputs.replace-values }}"
        for index in ${!SEARCH[*]}; do 
          echo "Replacing ${SEARCH[$index]} with ${REPLACE[$index]}"                        
          grep -rl ${SEARCH[$index]} ./ | xargs sed -i s~${SEARCH[$index]}~${REPLACE[$index]}~g
        done
      shell: bash
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"    
    - name: Install Quasar
      run: |
        sudo npm install --unsafe-perm=true --allow-root &&
        sudo npm install -g @quasar/cli        
      shell: bash
    - name: Install cordova
      run: sudo npm install -g cordova
      shell: bash
    - name: Update Java settings for cordova
      run: |
        sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/javac 100 &&
        sudo update-alternatives --set javac /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/javac &&
        sudo update-alternatives --config javac
      shell: bash
    - name: Quasar build for Android
      run: sudo npx quasar build -m cordova -T android --release
      shell: bash
    - name: Upload APK for Android
      uses: actions/upload-artifact@v1      
      with:
        name: quasar-build-android
        path: ./dist/cordova/android/bundle/release    
